/**
 * Copyright 2023 AntGroup CO., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package com.antfin.arc.cluster.proto;

/**
 * Protobuf type {@code JobSystemMetrics}
 */
public  final class JobSystemMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:JobSystemMetrics)
    JobSystemMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobSystemMetrics.newBuilder() to construct.
  private JobSystemMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobSystemMetrics() {
    workerMetrics_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobSystemMetrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              workerMetrics_ = new java.util.ArrayList<WorkerMetrics>();
              mutable_bitField0_ |= 0x00000001;
            }
            workerMetrics_.add(
                input.readMessage(WorkerMetrics.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        workerMetrics_ = java.util.Collections.unmodifiableList(workerMetrics_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Master.internal_static_JobSystemMetrics_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Master.internal_static_JobSystemMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            JobSystemMetrics.class, Builder.class);
  }

  public static final int WORKERMETRICS_FIELD_NUMBER = 1;
  private java.util.List<WorkerMetrics> workerMetrics_;
  /**
   * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
   */
  public java.util.List<WorkerMetrics> getWorkerMetricsList() {
    return workerMetrics_;
  }
  /**
   * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
   */
  public java.util.List<? extends WorkerMetricsOrBuilder>
      getWorkerMetricsOrBuilderList() {
    return workerMetrics_;
  }
  /**
   * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
   */
  public int getWorkerMetricsCount() {
    return workerMetrics_.size();
  }
  /**
   * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
   */
  public WorkerMetrics getWorkerMetrics(int index) {
    return workerMetrics_.get(index);
  }
  /**
   * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
   */
  public WorkerMetricsOrBuilder getWorkerMetricsOrBuilder(
      int index) {
    return workerMetrics_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < workerMetrics_.size(); i++) {
      output.writeMessage(1, workerMetrics_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < workerMetrics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, workerMetrics_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof JobSystemMetrics)) {
      return super.equals(obj);
    }
    JobSystemMetrics other = (JobSystemMetrics) obj;

    if (!getWorkerMetricsList()
        .equals(other.getWorkerMetricsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWorkerMetricsCount() > 0) {
      hash = (37 * hash) + WORKERMETRICS_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerMetricsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static JobSystemMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobSystemMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobSystemMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobSystemMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobSystemMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobSystemMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobSystemMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JobSystemMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static JobSystemMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static JobSystemMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static JobSystemMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JobSystemMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(JobSystemMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JobSystemMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JobSystemMetrics)
      JobSystemMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Master.internal_static_JobSystemMetrics_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Master.internal_static_JobSystemMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JobSystemMetrics.class, Builder.class);
    }

    // Construct using com.antfin.arc.cluster.proto.JobSystemMetrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWorkerMetricsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (workerMetricsBuilder_ == null) {
        workerMetrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        workerMetricsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Master.internal_static_JobSystemMetrics_descriptor;
    }

    @Override
    public JobSystemMetrics getDefaultInstanceForType() {
      return JobSystemMetrics.getDefaultInstance();
    }

    @Override
    public JobSystemMetrics build() {
      JobSystemMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public JobSystemMetrics buildPartial() {
      JobSystemMetrics result = new JobSystemMetrics(this);
      int from_bitField0_ = bitField0_;
      if (workerMetricsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          workerMetrics_ = java.util.Collections.unmodifiableList(workerMetrics_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.workerMetrics_ = workerMetrics_;
      } else {
        result.workerMetrics_ = workerMetricsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof JobSystemMetrics) {
        return mergeFrom((JobSystemMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(JobSystemMetrics other) {
      if (other == JobSystemMetrics.getDefaultInstance()) return this;
      if (workerMetricsBuilder_ == null) {
        if (!other.workerMetrics_.isEmpty()) {
          if (workerMetrics_.isEmpty()) {
            workerMetrics_ = other.workerMetrics_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWorkerMetricsIsMutable();
            workerMetrics_.addAll(other.workerMetrics_);
          }
          onChanged();
        }
      } else {
        if (!other.workerMetrics_.isEmpty()) {
          if (workerMetricsBuilder_.isEmpty()) {
            workerMetricsBuilder_.dispose();
            workerMetricsBuilder_ = null;
            workerMetrics_ = other.workerMetrics_;
            bitField0_ = (bitField0_ & ~0x00000001);
            workerMetricsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWorkerMetricsFieldBuilder() : null;
          } else {
            workerMetricsBuilder_.addAllMessages(other.workerMetrics_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      JobSystemMetrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (JobSystemMetrics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<WorkerMetrics> workerMetrics_ =
      java.util.Collections.emptyList();
    private void ensureWorkerMetricsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        workerMetrics_ = new java.util.ArrayList<WorkerMetrics>(workerMetrics_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        WorkerMetrics, WorkerMetrics.Builder, WorkerMetricsOrBuilder> workerMetricsBuilder_;

    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public java.util.List<WorkerMetrics> getWorkerMetricsList() {
      if (workerMetricsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(workerMetrics_);
      } else {
        return workerMetricsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public int getWorkerMetricsCount() {
      if (workerMetricsBuilder_ == null) {
        return workerMetrics_.size();
      } else {
        return workerMetricsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public WorkerMetrics getWorkerMetrics(int index) {
      if (workerMetricsBuilder_ == null) {
        return workerMetrics_.get(index);
      } else {
        return workerMetricsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder setWorkerMetrics(
        int index, WorkerMetrics value) {
      if (workerMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorkerMetricsIsMutable();
        workerMetrics_.set(index, value);
        onChanged();
      } else {
        workerMetricsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder setWorkerMetrics(
        int index, WorkerMetrics.Builder builderForValue) {
      if (workerMetricsBuilder_ == null) {
        ensureWorkerMetricsIsMutable();
        workerMetrics_.set(index, builderForValue.build());
        onChanged();
      } else {
        workerMetricsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder addWorkerMetrics(WorkerMetrics value) {
      if (workerMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorkerMetricsIsMutable();
        workerMetrics_.add(value);
        onChanged();
      } else {
        workerMetricsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder addWorkerMetrics(
        int index, WorkerMetrics value) {
      if (workerMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorkerMetricsIsMutable();
        workerMetrics_.add(index, value);
        onChanged();
      } else {
        workerMetricsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder addWorkerMetrics(
        WorkerMetrics.Builder builderForValue) {
      if (workerMetricsBuilder_ == null) {
        ensureWorkerMetricsIsMutable();
        workerMetrics_.add(builderForValue.build());
        onChanged();
      } else {
        workerMetricsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder addWorkerMetrics(
        int index, WorkerMetrics.Builder builderForValue) {
      if (workerMetricsBuilder_ == null) {
        ensureWorkerMetricsIsMutable();
        workerMetrics_.add(index, builderForValue.build());
        onChanged();
      } else {
        workerMetricsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder addAllWorkerMetrics(
        Iterable<? extends WorkerMetrics> values) {
      if (workerMetricsBuilder_ == null) {
        ensureWorkerMetricsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, workerMetrics_);
        onChanged();
      } else {
        workerMetricsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder clearWorkerMetrics() {
      if (workerMetricsBuilder_ == null) {
        workerMetrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        workerMetricsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public Builder removeWorkerMetrics(int index) {
      if (workerMetricsBuilder_ == null) {
        ensureWorkerMetricsIsMutable();
        workerMetrics_.remove(index);
        onChanged();
      } else {
        workerMetricsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public WorkerMetrics.Builder getWorkerMetricsBuilder(
        int index) {
      return getWorkerMetricsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public WorkerMetricsOrBuilder getWorkerMetricsOrBuilder(
        int index) {
      if (workerMetricsBuilder_ == null) {
        return workerMetrics_.get(index);  } else {
        return workerMetricsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public java.util.List<? extends WorkerMetricsOrBuilder>
         getWorkerMetricsOrBuilderList() {
      if (workerMetricsBuilder_ != null) {
        return workerMetricsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(workerMetrics_);
      }
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public WorkerMetrics.Builder addWorkerMetricsBuilder() {
      return getWorkerMetricsFieldBuilder().addBuilder(
          WorkerMetrics.getDefaultInstance());
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public WorkerMetrics.Builder addWorkerMetricsBuilder(
        int index) {
      return getWorkerMetricsFieldBuilder().addBuilder(
          index, WorkerMetrics.getDefaultInstance());
    }
    /**
     * <code>repeated .WorkerMetrics workerMetrics = 1;</code>
     */
    public java.util.List<WorkerMetrics.Builder>
         getWorkerMetricsBuilderList() {
      return getWorkerMetricsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        WorkerMetrics, WorkerMetrics.Builder, WorkerMetricsOrBuilder>
        getWorkerMetricsFieldBuilder() {
      if (workerMetricsBuilder_ == null) {
        workerMetricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            WorkerMetrics, WorkerMetrics.Builder, WorkerMetricsOrBuilder>(
                workerMetrics_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        workerMetrics_ = null;
      }
      return workerMetricsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:JobSystemMetrics)
  }

  // @@protoc_insertion_point(class_scope:JobSystemMetrics)
  private static final JobSystemMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new JobSystemMetrics();
  }

  public static JobSystemMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobSystemMetrics>
      PARSER = new com.google.protobuf.AbstractParser<JobSystemMetrics>() {
    @Override
    public JobSystemMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobSystemMetrics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobSystemMetrics> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<JobSystemMetrics> getParserForType() {
    return PARSER;
  }

  @Override
  public JobSystemMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

