/**
 * Copyright 2023 AntGroup CO., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package com.antfin.arc.cluster.coordinator.proto;

/**
 * <pre>
 * Query result.
 * </pre>
 *
 * Protobuf type {@code QueryResult}
 */
public  final class QueryResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:QueryResult)
    QueryResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryResult.newBuilder() to construct.
  private QueryResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryResult() {
    queryResult_ = "";
    queryError_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            queryId_ = input.readInt64();
            break;
          }
          case 16: {

            queryStatus_ = input.readBool();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            queryResult_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            queryError_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Coordinator.internal_static_QueryResult_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Coordinator.internal_static_QueryResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            QueryResult.class, Builder.class);
  }

  public static final int QUERYID_FIELD_NUMBER = 1;
  private long queryId_;
  /**
   * <pre>
   * It's be used to trace user query.
   * </pre>
   *
   * <code>int64 queryId = 1;</code>
   */
  public long getQueryId() {
    return queryId_;
  }

  public static final int QUERYSTATUS_FIELD_NUMBER = 2;
  private boolean queryStatus_;
  /**
   * <pre>
   * Status of the current query.
   * </pre>
   *
   * <code>bool queryStatus = 2;</code>
   */
  public boolean getQueryStatus() {
    return queryStatus_;
  }

  public static final int QUERYRESULT_FIELD_NUMBER = 3;
  private volatile Object queryResult_;
  /**
   * <pre>
   * Get the query result if status is true.
   * </pre>
   *
   * <code>string queryResult = 3;</code>
   */
  public String getQueryResult() {
    Object ref = queryResult_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      queryResult_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Get the query result if status is true.
   * </pre>
   *
   * <code>string queryResult = 3;</code>
   */
  public com.google.protobuf.ByteString
      getQueryResultBytes() {
    Object ref = queryResult_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      queryResult_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERYERROR_FIELD_NUMBER = 4;
  private volatile Object queryError_;
  /**
   * <pre>
   * Get the query error if status is false.
   * </pre>
   *
   * <code>string queryError = 4;</code>
   */
  public String getQueryError() {
    Object ref = queryError_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      queryError_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Get the query error if status is false.
   * </pre>
   *
   * <code>string queryError = 4;</code>
   */
  public com.google.protobuf.ByteString
      getQueryErrorBytes() {
    Object ref = queryError_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      queryError_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (queryId_ != 0L) {
      output.writeInt64(1, queryId_);
    }
    if (queryStatus_ != false) {
      output.writeBool(2, queryStatus_);
    }
    if (!getQueryResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, queryResult_);
    }
    if (!getQueryErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, queryError_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (queryId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, queryId_);
    }
    if (queryStatus_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, queryStatus_);
    }
    if (!getQueryResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, queryResult_);
    }
    if (!getQueryErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, queryError_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof QueryResult)) {
      return super.equals(obj);
    }
    QueryResult other = (QueryResult) obj;

    if (getQueryId()
        != other.getQueryId()) return false;
    if (getQueryStatus()
        != other.getQueryStatus()) return false;
    if (!getQueryResult()
        .equals(other.getQueryResult())) return false;
    if (!getQueryError()
        .equals(other.getQueryError())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUERYID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQueryId());
    hash = (37 * hash) + QUERYSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getQueryStatus());
    hash = (37 * hash) + QUERYRESULT_FIELD_NUMBER;
    hash = (53 * hash) + getQueryResult().hashCode();
    hash = (37 * hash) + QUERYERROR_FIELD_NUMBER;
    hash = (53 * hash) + getQueryError().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static QueryResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static QueryResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueryResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Query result.
   * </pre>
   *
   * Protobuf type {@code QueryResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:QueryResult)
      QueryResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Coordinator.internal_static_QueryResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Coordinator.internal_static_QueryResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryResult.class, Builder.class);
    }

    // Construct using com.antfin.arc.cluster.coordinator.proto.QueryResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      queryId_ = 0L;

      queryStatus_ = false;

      queryResult_ = "";

      queryError_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Coordinator.internal_static_QueryResult_descriptor;
    }

    @Override
    public QueryResult getDefaultInstanceForType() {
      return QueryResult.getDefaultInstance();
    }

    @Override
    public QueryResult build() {
      QueryResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public QueryResult buildPartial() {
      QueryResult result = new QueryResult(this);
      result.queryId_ = queryId_;
      result.queryStatus_ = queryStatus_;
      result.queryResult_ = queryResult_;
      result.queryError_ = queryError_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof QueryResult) {
        return mergeFrom((QueryResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(QueryResult other) {
      if (other == QueryResult.getDefaultInstance()) return this;
      if (other.getQueryId() != 0L) {
        setQueryId(other.getQueryId());
      }
      if (other.getQueryStatus() != false) {
        setQueryStatus(other.getQueryStatus());
      }
      if (!other.getQueryResult().isEmpty()) {
        queryResult_ = other.queryResult_;
        onChanged();
      }
      if (!other.getQueryError().isEmpty()) {
        queryError_ = other.queryError_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      QueryResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (QueryResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long queryId_ ;
    /**
     * <pre>
     * It's be used to trace user query.
     * </pre>
     *
     * <code>int64 queryId = 1;</code>
     */
    public long getQueryId() {
      return queryId_;
    }
    /**
     * <pre>
     * It's be used to trace user query.
     * </pre>
     *
     * <code>int64 queryId = 1;</code>
     */
    public Builder setQueryId(long value) {
      
      queryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * It's be used to trace user query.
     * </pre>
     *
     * <code>int64 queryId = 1;</code>
     */
    public Builder clearQueryId() {
      
      queryId_ = 0L;
      onChanged();
      return this;
    }

    private boolean queryStatus_ ;
    /**
     * <pre>
     * Status of the current query.
     * </pre>
     *
     * <code>bool queryStatus = 2;</code>
     */
    public boolean getQueryStatus() {
      return queryStatus_;
    }
    /**
     * <pre>
     * Status of the current query.
     * </pre>
     *
     * <code>bool queryStatus = 2;</code>
     */
    public Builder setQueryStatus(boolean value) {
      
      queryStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Status of the current query.
     * </pre>
     *
     * <code>bool queryStatus = 2;</code>
     */
    public Builder clearQueryStatus() {
      
      queryStatus_ = false;
      onChanged();
      return this;
    }

    private Object queryResult_ = "";
    /**
     * <pre>
     * Get the query result if status is true.
     * </pre>
     *
     * <code>string queryResult = 3;</code>
     */
    public String getQueryResult() {
      Object ref = queryResult_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        queryResult_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Get the query result if status is true.
     * </pre>
     *
     * <code>string queryResult = 3;</code>
     */
    public com.google.protobuf.ByteString
        getQueryResultBytes() {
      Object ref = queryResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        queryResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Get the query result if status is true.
     * </pre>
     *
     * <code>string queryResult = 3;</code>
     */
    public Builder setQueryResult(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      queryResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Get the query result if status is true.
     * </pre>
     *
     * <code>string queryResult = 3;</code>
     */
    public Builder clearQueryResult() {
      
      queryResult_ = getDefaultInstance().getQueryResult();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Get the query result if status is true.
     * </pre>
     *
     * <code>string queryResult = 3;</code>
     */
    public Builder setQueryResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      queryResult_ = value;
      onChanged();
      return this;
    }

    private Object queryError_ = "";
    /**
     * <pre>
     * Get the query error if status is false.
     * </pre>
     *
     * <code>string queryError = 4;</code>
     */
    public String getQueryError() {
      Object ref = queryError_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        queryError_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Get the query error if status is false.
     * </pre>
     *
     * <code>string queryError = 4;</code>
     */
    public com.google.protobuf.ByteString
        getQueryErrorBytes() {
      Object ref = queryError_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        queryError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Get the query error if status is false.
     * </pre>
     *
     * <code>string queryError = 4;</code>
     */
    public Builder setQueryError(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      queryError_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Get the query error if status is false.
     * </pre>
     *
     * <code>string queryError = 4;</code>
     */
    public Builder clearQueryError() {
      
      queryError_ = getDefaultInstance().getQueryError();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Get the query error if status is false.
     * </pre>
     *
     * <code>string queryError = 4;</code>
     */
    public Builder setQueryErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      queryError_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:QueryResult)
  }

  // @@protoc_insertion_point(class_scope:QueryResult)
  private static final QueryResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueryResult();
  }

  public static QueryResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryResult>
      PARSER = new com.google.protobuf.AbstractParser<QueryResult>() {
    @Override
    public QueryResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QueryResult> getParserForType() {
    return PARSER;
  }

  @Override
  public QueryResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

