/**
 * Copyright 2023 AntGroup CO., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package com.antfin.arc.cluster.coordinator.proto;

/**
 * Protobuf type {@code QueryRequest}
 */
public  final class QueryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:QueryRequest)
    QueryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryRequest.newBuilder() to construct.
  private QueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryRequest() {
    gremlinQuery_ = "";
    queryConfig_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            gremlinQuery_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              queryConfig_ = new java.util.ArrayList<QueryConfig>();
              mutable_bitField0_ |= 0x00000002;
            }
            queryConfig_.add(
                input.readMessage(QueryConfig.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        queryConfig_ = java.util.Collections.unmodifiableList(queryConfig_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Coordinator.internal_static_QueryRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Coordinator.internal_static_QueryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            QueryRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int GREMLINQUERY_FIELD_NUMBER = 1;
  private volatile Object gremlinQuery_;
  /**
   * <code>string gremlinQuery = 1;</code>
   */
  public String getGremlinQuery() {
    Object ref = gremlinQuery_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      gremlinQuery_ = s;
      return s;
    }
  }
  /**
   * <code>string gremlinQuery = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGremlinQueryBytes() {
    Object ref = gremlinQuery_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      gremlinQuery_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERYCONFIG_FIELD_NUMBER = 2;
  private java.util.List<QueryConfig> queryConfig_;
  /**
   * <code>repeated .QueryConfig queryConfig = 2;</code>
   */
  public java.util.List<QueryConfig> getQueryConfigList() {
    return queryConfig_;
  }
  /**
   * <code>repeated .QueryConfig queryConfig = 2;</code>
   */
  public java.util.List<? extends QueryConfigOrBuilder>
      getQueryConfigOrBuilderList() {
    return queryConfig_;
  }
  /**
   * <code>repeated .QueryConfig queryConfig = 2;</code>
   */
  public int getQueryConfigCount() {
    return queryConfig_.size();
  }
  /**
   * <code>repeated .QueryConfig queryConfig = 2;</code>
   */
  public QueryConfig getQueryConfig(int index) {
    return queryConfig_.get(index);
  }
  /**
   * <code>repeated .QueryConfig queryConfig = 2;</code>
   */
  public QueryConfigOrBuilder getQueryConfigOrBuilder(
      int index) {
    return queryConfig_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getGremlinQueryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, gremlinQuery_);
    }
    for (int i = 0; i < queryConfig_.size(); i++) {
      output.writeMessage(2, queryConfig_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGremlinQueryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, gremlinQuery_);
    }
    for (int i = 0; i < queryConfig_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, queryConfig_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof QueryRequest)) {
      return super.equals(obj);
    }
    QueryRequest other = (QueryRequest) obj;

    if (!getGremlinQuery()
        .equals(other.getGremlinQuery())) return false;
    if (!getQueryConfigList()
        .equals(other.getQueryConfigList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GREMLINQUERY_FIELD_NUMBER;
    hash = (53 * hash) + getGremlinQuery().hashCode();
    if (getQueryConfigCount() > 0) {
      hash = (37 * hash) + QUERYCONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getQueryConfigList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static QueryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static QueryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code QueryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:QueryRequest)
      QueryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Coordinator.internal_static_QueryRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Coordinator.internal_static_QueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryRequest.class, Builder.class);
    }

    // Construct using com.antfin.arc.cluster.coordinator.proto.QueryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getQueryConfigFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      gremlinQuery_ = "";

      if (queryConfigBuilder_ == null) {
        queryConfig_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        queryConfigBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Coordinator.internal_static_QueryRequest_descriptor;
    }

    @Override
    public QueryRequest getDefaultInstanceForType() {
      return QueryRequest.getDefaultInstance();
    }

    @Override
    public QueryRequest build() {
      QueryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public QueryRequest buildPartial() {
      QueryRequest result = new QueryRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.gremlinQuery_ = gremlinQuery_;
      if (queryConfigBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          queryConfig_ = java.util.Collections.unmodifiableList(queryConfig_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.queryConfig_ = queryConfig_;
      } else {
        result.queryConfig_ = queryConfigBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof QueryRequest) {
        return mergeFrom((QueryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(QueryRequest other) {
      if (other == QueryRequest.getDefaultInstance()) return this;
      if (!other.getGremlinQuery().isEmpty()) {
        gremlinQuery_ = other.gremlinQuery_;
        onChanged();
      }
      if (queryConfigBuilder_ == null) {
        if (!other.queryConfig_.isEmpty()) {
          if (queryConfig_.isEmpty()) {
            queryConfig_ = other.queryConfig_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureQueryConfigIsMutable();
            queryConfig_.addAll(other.queryConfig_);
          }
          onChanged();
        }
      } else {
        if (!other.queryConfig_.isEmpty()) {
          if (queryConfigBuilder_.isEmpty()) {
            queryConfigBuilder_.dispose();
            queryConfigBuilder_ = null;
            queryConfig_ = other.queryConfig_;
            bitField0_ = (bitField0_ & ~0x00000002);
            queryConfigBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getQueryConfigFieldBuilder() : null;
          } else {
            queryConfigBuilder_.addAllMessages(other.queryConfig_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      QueryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (QueryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object gremlinQuery_ = "";
    /**
     * <code>string gremlinQuery = 1;</code>
     */
    public String getGremlinQuery() {
      Object ref = gremlinQuery_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gremlinQuery_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string gremlinQuery = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGremlinQueryBytes() {
      Object ref = gremlinQuery_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gremlinQuery_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gremlinQuery = 1;</code>
     */
    public Builder setGremlinQuery(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gremlinQuery_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gremlinQuery = 1;</code>
     */
    public Builder clearGremlinQuery() {
      
      gremlinQuery_ = getDefaultInstance().getGremlinQuery();
      onChanged();
      return this;
    }
    /**
     * <code>string gremlinQuery = 1;</code>
     */
    public Builder setGremlinQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gremlinQuery_ = value;
      onChanged();
      return this;
    }

    private java.util.List<QueryConfig> queryConfig_ =
      java.util.Collections.emptyList();
    private void ensureQueryConfigIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        queryConfig_ = new java.util.ArrayList<QueryConfig>(queryConfig_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        QueryConfig, QueryConfig.Builder, QueryConfigOrBuilder> queryConfigBuilder_;

    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public java.util.List<QueryConfig> getQueryConfigList() {
      if (queryConfigBuilder_ == null) {
        return java.util.Collections.unmodifiableList(queryConfig_);
      } else {
        return queryConfigBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public int getQueryConfigCount() {
      if (queryConfigBuilder_ == null) {
        return queryConfig_.size();
      } else {
        return queryConfigBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public QueryConfig getQueryConfig(int index) {
      if (queryConfigBuilder_ == null) {
        return queryConfig_.get(index);
      } else {
        return queryConfigBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder setQueryConfig(
        int index, QueryConfig value) {
      if (queryConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryConfigIsMutable();
        queryConfig_.set(index, value);
        onChanged();
      } else {
        queryConfigBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder setQueryConfig(
        int index, QueryConfig.Builder builderForValue) {
      if (queryConfigBuilder_ == null) {
        ensureQueryConfigIsMutable();
        queryConfig_.set(index, builderForValue.build());
        onChanged();
      } else {
        queryConfigBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder addQueryConfig(QueryConfig value) {
      if (queryConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryConfigIsMutable();
        queryConfig_.add(value);
        onChanged();
      } else {
        queryConfigBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder addQueryConfig(
        int index, QueryConfig value) {
      if (queryConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryConfigIsMutable();
        queryConfig_.add(index, value);
        onChanged();
      } else {
        queryConfigBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder addQueryConfig(
        QueryConfig.Builder builderForValue) {
      if (queryConfigBuilder_ == null) {
        ensureQueryConfigIsMutable();
        queryConfig_.add(builderForValue.build());
        onChanged();
      } else {
        queryConfigBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder addQueryConfig(
        int index, QueryConfig.Builder builderForValue) {
      if (queryConfigBuilder_ == null) {
        ensureQueryConfigIsMutable();
        queryConfig_.add(index, builderForValue.build());
        onChanged();
      } else {
        queryConfigBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder addAllQueryConfig(
        Iterable<? extends QueryConfig> values) {
      if (queryConfigBuilder_ == null) {
        ensureQueryConfigIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, queryConfig_);
        onChanged();
      } else {
        queryConfigBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder clearQueryConfig() {
      if (queryConfigBuilder_ == null) {
        queryConfig_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        queryConfigBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public Builder removeQueryConfig(int index) {
      if (queryConfigBuilder_ == null) {
        ensureQueryConfigIsMutable();
        queryConfig_.remove(index);
        onChanged();
      } else {
        queryConfigBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public QueryConfig.Builder getQueryConfigBuilder(
        int index) {
      return getQueryConfigFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public QueryConfigOrBuilder getQueryConfigOrBuilder(
        int index) {
      if (queryConfigBuilder_ == null) {
        return queryConfig_.get(index);  } else {
        return queryConfigBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public java.util.List<? extends QueryConfigOrBuilder>
         getQueryConfigOrBuilderList() {
      if (queryConfigBuilder_ != null) {
        return queryConfigBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(queryConfig_);
      }
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public QueryConfig.Builder addQueryConfigBuilder() {
      return getQueryConfigFieldBuilder().addBuilder(
          QueryConfig.getDefaultInstance());
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public QueryConfig.Builder addQueryConfigBuilder(
        int index) {
      return getQueryConfigFieldBuilder().addBuilder(
          index, QueryConfig.getDefaultInstance());
    }
    /**
     * <code>repeated .QueryConfig queryConfig = 2;</code>
     */
    public java.util.List<QueryConfig.Builder>
         getQueryConfigBuilderList() {
      return getQueryConfigFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        QueryConfig, QueryConfig.Builder, QueryConfigOrBuilder>
        getQueryConfigFieldBuilder() {
      if (queryConfigBuilder_ == null) {
        queryConfigBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            QueryConfig, QueryConfig.Builder, QueryConfigOrBuilder>(
                queryConfig_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        queryConfig_ = null;
      }
      return queryConfigBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:QueryRequest)
  }

  // @@protoc_insertion_point(class_scope:QueryRequest)
  private static final QueryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueryRequest();
  }

  public static QueryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryRequest>
      PARSER = new com.google.protobuf.AbstractParser<QueryRequest>() {
    @Override
    public QueryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QueryRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public QueryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

