/**
 * Copyright 2023 AntGroup CO., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coordinator.proto

package com.antfin.arc.cluster.coordinator.proto;

public interface QueryResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * It's be used to trace user query.
   * </pre>
   *
   * <code>int64 queryId = 1;</code>
   */
  long getQueryId();

  /**
   * <pre>
   * Status of the current query.
   * </pre>
   *
   * <code>bool queryStatus = 2;</code>
   */
  boolean getQueryStatus();

  /**
   * <pre>
   * Get the query result if status is true.
   * </pre>
   *
   * <code>string queryResult = 3;</code>
   */
  String getQueryResult();
  /**
   * <pre>
   * Get the query result if status is true.
   * </pre>
   *
   * <code>string queryResult = 3;</code>
   */
  com.google.protobuf.ByteString
      getQueryResultBytes();

  /**
   * <pre>
   * Get the query error if status is false.
   * </pre>
   *
   * <code>string queryError = 4;</code>
   */
  String getQueryError();
  /**
   * <pre>
   * Get the query error if status is false.
   * </pre>
   *
   * <code>string queryError = 4;</code>
   */
  com.google.protobuf.ByteString
      getQueryErrorBytes();
}
